# Force Nixpacks to build as Node.js API server
providers = []

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["cd packages/api && npx prisma generate && npm run build"]

[start]
cmd = "cd packages/api && npm run start"
