[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc"]

[start]
cmd = "node dist/app.js"
